Parameters:
  ALBAccessLogsBucketName1:
    Type: String
    Description: "The name of the ALB access logs S3 bucket"

# ------------------------------------------------------------#
#  ALB
# ------------------------------------------------------------#

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: project-ALB-01
      Scheme: internal
      Type: application
      Subnets:
        - !ImportValue PrivateSubnet1-ID
        - !ImportValue PrivateSubnet2-ID
      SecurityGroups:
        - !ImportValue SG-ALB-01
      Tags:
        - Key: Name
          Value: project-ALB-01
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !Ref ALBAccessLogsBucketName1
        - Key: access_logs.s3.prefix
          Value: 'prod'     

# ------------------------------------------------------------#
#  ALBListener
# ------------------------------------------------------------#

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TG1
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

# ------------------------------------------------------------#
#  TargetGroup
# ------------------------------------------------------------#

  TG1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: project-TG-01
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !ImportValue VPC-ID
      HealthCheckPath: /healthz/
      Tags:
        - Key: Name
          Value: project-TG-01

Outputs:
  ALBDNSName:
    Description: "The DNS name of the ALB"
    Value: !GetAtt ALB.DNSName
    Export:
      Name: ALB-DNS-Name

  ALBArn:
      Description: "The ARN of the ALB"
      Value: !Ref ALB
      Export:
        Name: ALBArn
  
  ALBListenerArn:
    Description: The ARN of the ALB Listener
    Value: !Ref ALBListener
    Export:
      Name: ALB-Listener-ARN

  TG1Arn:
    Description: The ARN of the Target Group 1
    Value: !Ref TG1
    Export:
      Name: TG1-ARN
